add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/ip/fifo_hs/fifo_hs.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/ip/fifo_sc_fifo1/fifo_sc_fifo1.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/ip/fifo_sc_fifo2/fifo_sc_fifo2.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/ip/fifo_top/fifo_top.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/ip/gowin_rpll25M/gowin_rpll25M.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/ip/gowin_rpll50M/gowin_rpll50M.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/main.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/arp/arp.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/arp/arp_rx.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/arp/arp_tx.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos2eth/cmos2eth.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos2eth/cmos_data_rev.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos2eth/cmos_udp_send.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos2gray/cmos2gray.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos2gray/data2gray.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos2gray/gray_send.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos2sobel/cmos2sobel.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos2sobel/data2gray.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos2sobel/gray2sobel.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos2sobel/sobel_send.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos_config/cmos_config.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos_config/config_ctrl.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos_config/config_ctrl_480p30fps.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos_config/config_ctrl_720p15fps.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos_config/config_ctrl_vga30fps.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/cmos_config/i2c_send.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/eth_trans/crc32.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/eth_trans/eth_trans.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/eth_trans/rgmii_rx.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/eth_trans/rgmii_tx.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/icmp/icmp.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/icmp/icmp_rx.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/icmp/icmp_tx.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/rtl/key_filter/key_filter.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/sim/tb_cmos2sobel.v
add_file D:/Acode/Gowin/9_doubleOv5640_transformer_UDP/src/sim/tb_main.v
